/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KamarIndexRouteImport } from './routes/kamar.index'
import { Route as KamarIdRouteImport } from './routes/kamar.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIndexRoute = KamarIndexRouteImport.update({
  id: '/kamar/',
  path: '/kamar/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIdRoute = KamarIdRouteImport.update({
  id: '/kamar/$id',
  path: '/kamar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/kamar/$id': typeof KamarIdRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/kamar/$id': typeof KamarIdRoute
  '/kamar': typeof KamarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/kamar/$id': typeof KamarIdRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/kamar/$id' | '/kamar/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/kamar/$id' | '/kamar'
  id: '__root__' | '/' | '/login' | '/register' | '/kamar/$id' | '/kamar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  KamarIdRoute: typeof KamarIdRoute
  KamarIndexRoute: typeof KamarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/': {
      id: '/kamar/'
      path: '/kamar'
      fullPath: '/kamar/'
      preLoaderRoute: typeof KamarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/$id': {
      id: '/kamar/$id'
      path: '/kamar/$id'
      fullPath: '/kamar/$id'
      preLoaderRoute: typeof KamarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  KamarIdRoute: KamarIdRoute,
  KamarIndexRoute: KamarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
