/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BookingSayaRouteImport } from './routes/booking-saya'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KamarIndexRouteImport } from './routes/kamar.index'
import { Route as PembayaranIdRouteImport } from './routes/pembayaran.$id'
import { Route as KamarIdRouteImport } from './routes/kamar.$id'
import { Route as BookingIdRouteImport } from './routes/booking.$id'
import { Route as BookingBerhasilIdRouteImport } from './routes/booking-berhasil.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSayaRoute = BookingSayaRouteImport.update({
  id: '/booking-saya',
  path: '/booking-saya',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIndexRoute = KamarIndexRouteImport.update({
  id: '/kamar/',
  path: '/kamar/',
  getParentRoute: () => rootRouteImport,
} as any)
const PembayaranIdRoute = PembayaranIdRouteImport.update({
  id: '/pembayaran/$id',
  path: '/pembayaran/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarIdRoute = KamarIdRouteImport.update({
  id: '/kamar/$id',
  path: '/kamar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingIdRoute = BookingIdRouteImport.update({
  id: '/booking/$id',
  path: '/booking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingBerhasilIdRoute = BookingBerhasilIdRouteImport.update({
  id: '/booking-berhasil/$id',
  path: '/booking-berhasil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking-saya': typeof BookingSayaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/booking-berhasil/$id': typeof BookingBerhasilIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/kamar/$id': typeof KamarIdRoute
  '/pembayaran/$id': typeof PembayaranIdRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking-saya': typeof BookingSayaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/booking-berhasil/$id': typeof BookingBerhasilIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/kamar/$id': typeof KamarIdRoute
  '/pembayaran/$id': typeof PembayaranIdRoute
  '/kamar': typeof KamarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/booking-saya': typeof BookingSayaRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/booking-berhasil/$id': typeof BookingBerhasilIdRoute
  '/booking/$id': typeof BookingIdRoute
  '/kamar/$id': typeof KamarIdRoute
  '/pembayaran/$id': typeof PembayaranIdRoute
  '/kamar/': typeof KamarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/booking-saya'
    | '/login'
    | '/register'
    | '/booking-berhasil/$id'
    | '/booking/$id'
    | '/kamar/$id'
    | '/pembayaran/$id'
    | '/kamar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/booking-saya'
    | '/login'
    | '/register'
    | '/booking-berhasil/$id'
    | '/booking/$id'
    | '/kamar/$id'
    | '/pembayaran/$id'
    | '/kamar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/booking-saya'
    | '/login'
    | '/register'
    | '/booking-berhasil/$id'
    | '/booking/$id'
    | '/kamar/$id'
    | '/pembayaran/$id'
    | '/kamar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BookingSayaRoute: typeof BookingSayaRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BookingBerhasilIdRoute: typeof BookingBerhasilIdRoute
  BookingIdRoute: typeof BookingIdRoute
  KamarIdRoute: typeof KamarIdRoute
  PembayaranIdRoute: typeof PembayaranIdRoute
  KamarIndexRoute: typeof KamarIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-saya': {
      id: '/booking-saya'
      path: '/booking-saya'
      fullPath: '/booking-saya'
      preLoaderRoute: typeof BookingSayaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/': {
      id: '/kamar/'
      path: '/kamar'
      fullPath: '/kamar/'
      preLoaderRoute: typeof KamarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembayaran/$id': {
      id: '/pembayaran/$id'
      path: '/pembayaran/$id'
      fullPath: '/pembayaran/$id'
      preLoaderRoute: typeof PembayaranIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar/$id': {
      id: '/kamar/$id'
      path: '/kamar/$id'
      fullPath: '/kamar/$id'
      preLoaderRoute: typeof KamarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$id': {
      id: '/booking/$id'
      path: '/booking/$id'
      fullPath: '/booking/$id'
      preLoaderRoute: typeof BookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-berhasil/$id': {
      id: '/booking-berhasil/$id'
      path: '/booking-berhasil/$id'
      fullPath: '/booking-berhasil/$id'
      preLoaderRoute: typeof BookingBerhasilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BookingSayaRoute: BookingSayaRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BookingBerhasilIdRoute: BookingBerhasilIdRoute,
  BookingIdRoute: BookingIdRoute,
  KamarIdRoute: KamarIdRoute,
  PembayaranIdRoute: PembayaranIdRoute,
  KamarIndexRoute: KamarIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
